# Generated by Django 3.1.6 on 2021-02-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('writer', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('publish_date', models.DateField()),
                ('averageRating', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
